services:
  server:
    build: .
    container_name: go-server
    entrypoint: sh -c "go run server.go"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/
    working_dir: /go/src/
    healthcheck:
      test: curl --fail http://localhost:8080/cotacao || exit 1
      interval: 5s
      retries: 10
      timeout: 1s
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  client:
    build: .
    container_name: go-client
    entrypoint: sh -c "go run client.go"
    volumes:
      - .:/go/src/
    working_dir: /go/src/
    depends_on:
      server:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
