services:
  server:
    build: .
    container_name: go-server
    entrypoint: sh -c "go run server.go"
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/
    working_dir: /go/src/
  client:
    build: .
    container_name: go-client
    entrypoint: sh -c "go run client.go"
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/
    working_dir: /go/src/
